apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-deployment-sj
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet-deployment-sj
  template:
    metadata:
      labels:
        app: dotnet-deployment-sj
    spec:
      containers:
      - name: dotnet
        image: completedotnetsampleapp.azurecr.io/dotnet:2.0
        ports:
        - containerPort: 5000
